name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  IMAGE: cowsay
jobs:
  cowsay-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Versioning
        run: |
          git fetch --prune --unshallow --tags
          TAGS=$(git tag)
          echo "TAGS: $TAGS"
          if [ -z "$TAGS" ]; then
            OLD_VER=$(cat v.txt)
            OLD_VER="${OLD_VER}.0"
            VERSION="$OLD_VER"
          else
            OLD_VER=$(git tag | sort -V | tail -n 1)
            VERSION=$(echo "$OLD_VER" | awk -F. '{print $1 "." $2 "." $3+1}')
          fi
          echo "$VERSION" > v.txt
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "OLD_VER=$OLD_VER" >> $GITHUB_ENV
          
      - name: Show New Version
        run: echo "New version is $VERSION"
      
      - name: Dockerize Cowsay
        run: docker build -t $IMAGE:$VERSION .
        
      
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
